<?php

use App\Resource;
use Illuminate\Database\Seeder;

class ResourceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->resources as $title) {
            Resource::create(['title' => $title]);
        }
    }

    private $resources = [
        "JDE One World",
        "GCPs",
        "WiFi",
        "Westlaw",
        "Weapons of Mass Destruction",
        "NSS",
        "JavaScript",
        "Www",
        "CQT",
        "Test Driven Development",
        "RPG III",
        "Tourism",
        "XNA",
        "IAR Embedded Workbench",
        "ALM",
        "IEC 62304",
        "VTAM",
        "E-zines",
        "CFD",
        "VBAC",
        "Driving Results",
        "Early Childhood Education",
        "Personal Training",
        "Karate",
        "Film Festivals",
        "Inventory Management",
        "Non-profit Program Development",
        "RPM",
        "Piano Education",
        "Microsoft Word",
        "BMP design",
        "UV/Vis",
        "Health Economics",
        "McAfee Antivirus",
        "JIS",
        "Railway",
        "SAP ERP",
        "iGaming",
        "QCAT",
        "Furniture",
        "MFS",
        "GCS",
        "Black Box Testing",
        "RHCE",
        "RDO",
        "Kronos WFC",
        "Oracle SQL Developer",
        "HDSL",
        "Dance",
        "BMV",
        "Hygiene",
        "Klarity",
        "Analytical Ultracentrifugation",
        "Phone Etiquette",
        "Young Adult Literature",
        "Permanent Placement",
        "OKI",
        "BPL",
        "Zebra",
        "Wicklander-Zulawski Interview",
        "Microsoft Publisher",
        "DMT",
        "RT-PCR",
        "uDig",
        "NREMT",
        "QHSE",
        "BWA",
        "Piano Playing",
        "Tds",
        "Physicians",
        "Ukrainian",
        "Patents",
        "TSO",
        "Typo3",
        "Lubricants",
        "Radio Promotions",
        "KMS",
        "Music History",
        "Award Submissions",
        "HCS12",
        "ETL Tools",
        "OECD",
        "Nonprofits",
        "Web Content Management",
        "Bass Guitar",
        "Mycobacteriology",
        "Data Center",
        "ERP",
        "Threat &amp; Vulnerability Management",
        "Job Descriptions",
        "Rule Of Law",
        "Term Life Insurance",
        "Outsourcing",
        "UI Automation",
        "GS1",
        "WFC",
        "QSAR",
        "Axles",
        "Hazard Identification",
        "PMAs",
        "LVDS",
        "Global Sourcing",
        "Media Relations",
        "LP",
        "LSO",
        "Working With Children",
        "NDA",
        "KOL Identification",
        "LLC",
        "IFE",
        "IIS",
        "RSVP",
        "Agronomy",
        "Mortgage Banking",
        "z/VM",
        "sFlow",
        "Pre-owned",
        "HD Camera Operation",
        "KDE",
        "ILOG",
        "Mortgage Lending",
        "CADS RC",
        "FDS",
        "Microsoft Dynamics GP",
        "Character Rigging",
        "KNX",
        "RCA",
        "Urban Infill",
        "Biochemistry",
        "SnagIt",
        "Qooxdoo",
        "Clinical Research",
        "Bass Guitar",
        "Time &amp; Attendance",
        "Deep Tissue Massage",
        "Waterfront",
        "Sheet Metal",
        "High Net Worth Individuals",
        "IEF",
        "WSGI",
        "RTP",
        "Brain Gym",
        "Governmental Affairs",
        "Silhouette FX",
        "TMG",
        "IB",
        "Animal Behavior",
        "AMBA AHB",
        "FCRA",
        "AAUS Scientific Diver",
        "Homeland Security",
        "Legislative Affairs",
        "Honeywell DCS",
        "Yoga",
        "CFML",
        "Kontakt",
        "Zope",
        "JTAG",
        "FDT",
        "ECDL Certification",
        "HDX",
        "Bankruptcy",
        "Hydraulics",
        "RLU",
        "GSS",
        "IAR",
        "Kaizen Leadership",
        "EIS",
        "Pediatrics",
        "Nylon",
        "Ecological Restoration",
        "ePub",
        "ICH-GCP",
        "NGP",
        "Air Force",
        "Japanese to English",
        "SIP Trunking",
        "MDR",
        "Management by Objectives",
        "EEO Reporting",
        "RCRA",
        "DGA",
        "Wastewater Treatment",
        "IEC 62304",
        "EU Competition Law",
        "TCP",
        "Turbo C++",
        "GNU C++",
        "ERDAS Imagine",
        "MLSS",
        "Pianist",
        "Event Photography",
        "UML Tools",
        "Due Diligence",
        "Sustainable Agriculture",
        "PFT",
        "OAS",
        "Hardware",
        "Urban Design",
        "Protein Purification",
        "Environmental Science",
        "NSPS",
        "JUnit",
        "Nursing",
        "Newspapers",
        "Gift Baskets",
        "SAP HR",
        "ICH Guidelines",
        "Lean Manufacturing",
        "Jerseys",
        "Facebook",
        "Data Mining",
        "qPCR",
        "Luciferase Assay",
        "MTT",
        "vCenter Server",
        "Cyber-security",
        "Screenwriting",
        "iPad Development",
        "Radio Advertising",
        "Resume Writing",
        "FCE",
        "DVD Authoring",
        "ODIN",
        "NC-Verilog",
        "Distance Learning",
        "Gourmet",
        "Tally ERP",
        "Waste Management",
        "Turn Around Management",
        "TNS",
        "Oncology",
        "Job Coaching",
        "SDL Trados",
        "Earthworks",
        "UFS",
        "Snacks",
        "UWB",
        "LDAR",
        "IHE",
        "Intergovernmental Affairs",
        "Sports Psychology",
        "DX200",
        "JDA",
        "Glasses",
        "Early-stage Startups",
        "CVaR",
        "Lighting",
        "WPS",
        "Servers",
        "Quality Control",
        "RRDTool",
        "Xajax",
        "Device Drivers",
        "Canon XL2",
        "BMX",
        "QPS",
        "HEC-HMS",
        "IATSE",
        "VPN",
        "RS422",
        "Visual Arts",
        "Jeans",
        "Childcare",
        "Google Docs",
        "Spring DM",
        "Swaps",
        "Executive Coaching",
        "PCRF",
        "VM",
        "Overhaul",
        "mTAB",
        "Marketing Strategy",
        "Operational Excellence",
        "NPV",
        "Store Operations",
        "Hedge Funds",
        "Emergency Management",
        "Trading",
        "VTL",
        "JVC",
        "IEC 60601",
        "Criminal Investigations",
        "Phase II Environmental Site Assessments",
        "Ventilation",
        "Light Rail",
        "DGGE",
        "Kinesio Taping",
        "GIS Application",
        "Cfengine",
        "EPCM",
        "ArcGIS",
        "AAP",
        "Small Business Online Marketing",
        "DBVisualizer",
        "NLTK",
        "FME",
        "Steam Turbines",
        "Cluster",
        "Process Automation",
        "Oxygen XML Editor",
        "Motivational Interviewing",
        "Volleyball",
        "Supporting Others",
        "PFS",
        "MCDST",
        "MCITP",
        "HR Transformation",
        "Drafting Agreements",
        "Corporate Finance",
        "Executive Management",
        "Product Life Cycle",
        "RVs",
        "Jazz Dance",
        "Hoshin Kanri",
        "TWS",
        "Bylined Articles",
        "Athletic Administration",
        "Strategic HR",
        "OJEU",
        "HCS 2000",
        "Skin Care",
        "Piano",
        "SPC",
        "Organizational Design",
        "Workforce Management",
        "UED",
        "Oxidative Stress",
        "Floor Plans",
        "DMR",
        "CNC Programing",
        "Ambulance",
        "Knowledge Transfer",
        "Apache",
        "Security Audits",
        "DxDesigner",
        "Outdoor Recreation",
        "Amazon Web Services (AWS)",
        "RFID Applications",
        "CTIOS",
        "ArcGIS",
        "HDTV",
        "TMA",
        "Drama",
        "Yammer",
        "RMS",
        "Work Very Well with Others",
        "BSCI",
        "DFSS Green Belt",
        "Ulcerative Colitis",
        "Oil on Canvas",
        "SAP BW",
        "Retail Sales",
        "AED",
        "SD",
        "TPE",
        "Zillow",
        "PyUnit",
        "Hyperion Reports",
        "Gcov",
        "Job Search Strategies",
        "Laboratory Skills",
        "Payment by Results",
        "Rubber",
        "CDPE Designation",
        "Pitching Ideas",
        "ZoomInfo",
        "Project Planning",
        "HTML Help Workshop",
        "HFC",
        "Radiology",
        "Rugs",
        "DBVisualizer",
        "HDI",
        "HD Video",
        "SNP genotyping",
        "MPE",
        "Fertility",
        "UPS Systems",
        "IPSec",
        "Koha",
        "HW Design",
        "Utilities Management",
        "EIGRP",
        "Construction Management",
        "Dump Truck",
        "Force Protection",
        "RIP",
        "SAP Implementation",
        "PyMEL",
        "Basel III",
        "FX Spot",
        "Social Media Outreach",
        "HP Networking",
        "CMake",
        "Kaspersky Antivirus",
        "BD+C",
        "Air Compressors",
        "HDLC",
        "Supplier Evaluation",
        "Financial Risk",
        "GPS Tracking",
        "Project Bidding",
        "CRM",
        "vCloud",
        "Accounts Receivable",
        "Medical-Surgical",
        "Agronomy",
        "Dry Eye",
        "Hazard Recognition",
        "RPD",
        "DFR",
        "Receptionist Duties",
        "Swimming",
        "Improvisation",
        "VTR",
        "NTSC",
        "MHRA",
        "Ext JS",
        "Legal Documents",
        "VST",
        "Myriad",
        "AQTESOLV",
        "Visual Arts",
        "Radio Production",
        "VXI",
        "eBanking",
        "ITIL",
        "EPANET",
        "Business Development",
        "MBE",
        "NICU",
        "HSP",
        "Internet Yellow Pages",
        "Nielsen",
        "FPGA",
        "First Time Home Buyers",
        "Customer Support",
        "Events Organisation",
        "Environmental Awareness",
        "Utility Construction",
        "EMS",
        "IEEE",
        "JCR",
        "Koine Greek",
        "Multi-Unit Management",
        "Oracle ERP",
        "Commercial Photography",
        "Thermal Oxidizers",
        "Location Intelligence",
        "FTC",
        "Vlookup",
        "Validation",
        "Cycling",
        "T-SQL",
        "Protein Purification",
        "Total Cost of Ownership",
        "Liability",
        "Simulations",
        "PKI",
        "Switchgear",
        "Yamaha M7CL",
        "WS",
        "Frame Relay",
        "Gospel",
        "BBx",
        "Fixed Assets",
        "Global Human Resources Management",
        "BSD",
        "SSEP",
        "Luxury Homes",
        "IGCC",
        "FFIEC",
        "AJAX Toolkit",
        "FDCPA",
        "CCIE",
        "Tax Returns",
        "CGI/Perl",
        "Environmental Policy",
        "Cerner",
        "PFEMA",
        "VXML",
        "Social TV",
        "RPR",
        "Tax Accounting",
        "XPlanner",
        "RCSA",
        "Business Analysis",
        "Oil Paint",
        "LDRA",
        "Townhomes",
        "Type Approval",
        "ASIC",
        "RF",
        "Foreign Trade Zone",
        "Petroleum",
        "TSS",
        "Managerial Finance",
        "DVD Duplication",
        "AODA",
        "LAN-WAN",
        "CME",
        "Switchboard Operator",
        "Red Hat Linux",
        "MLB",
        "Data Migration",
        "Venture Capital",
        "FMV",
        "5 Why",
        "CCTV",
        "Guest Recovery",
        "Reality TV",
        "Utility Locating",
        "White Box Testing",
        "Commercial Litigation",
        "MPEG Streamclip",
        "VSA",
        "Disaster Recovery",
        "Solution Selling",
        "DDI Certified",
        "Subversion",
        "MXP",
        "HtmlUnit",
        "JRockit",
        "SAP OM",
        "Compensation &amp; Benefits",
        "Web Content",
        "SEO",
        "jQTouch",
        "BPO",
        "Talent Acquisition",
        "Strategic Human Resources Leadership",
        "3Com NBX",
        "Urgent Care",
        "PCI Standards",
        "BPEL",
        "VTC",
        "Political Economy",
        "PBUSE",
        "Conservation Issues",
        "GT Strudl",
        "Footwear",
        "Vulnerability Scanning",
        "KWP2000",
        "Art Exhibitions",
        "HTML5",
        "DTA",
        "BC/DR",
        "EES",
        "CPA",
        "Mining",
        "Road",
        "TNCC Instruction",
        "Big Data",
        "Hazard Analysis",
        "Tortoise SVN",
        "Kidney Transplant",
        "Payments",
        "BMC Remedy",
        "Overall Wellness",
        "Myers-Briggs Certified",
        "Slackware",
        "Physics",
        "Rational DOORS",
        "Commercial Real Estate",
        "MC2",
        "Video over IP",
        "Universal Life",
        "RF Design",
        "Earthquake Engineering",
        "Registered Nurses",
        "XSL",
        "VSOE",
        "IRAs",
        "PDP",
        "MX960",
        "XLMiner",
        "JPOS",
        "Knitting",
        "Urban Redevelopment",
        "Leave of Absence",
        "MPBGP",
        "AHU",
        "Geotechnical Engineering",
        "Personal Injury",
        "CSPro",
        "IT Audit",
        "QC Tools",
        "VB.NET",
        "Health Economics",
        "Microsoft SQL Server",
        "Elder Care",
        "Ebooks",
        "Ocular Disease",
        "RVs",
        "QRM",
        "Maritime Operations",
        "Internet Banking",
        "GBA",
        "XPlanner",
        "DWBI",
        "Blues",
        "Crystal Reports",
        "Aircraft Maintenance",
        "HMS",
        "IBC",
        "Managed Care",
        "Unix",
        "Apartments",
        "Aerial Photography",
        "Digital Photography",
        "Kuka",
        "MMIS",
        "Job Coaching",
        "XOG",
        "Nutritional Counseling",
        "Short Sales",
        "WSDL",
        "Aerospace Engineering",
        "Cellular Communications",
        "VLC",
        "CSRs",
        "Experimentation",
        "Fluorescence Microscopy",
        "DOT Regulations",
        "Disability Insurance",
        "XCAL",
        "Freight",
        "Inspection",
        "DoD",
        "SQL Azure",
        "UNIX Utilities",
        "Owner Representation",
        "SGBD",
        "Linux Kernel",
        "CPT",
        "Coastal Zone Management",
        "NVH",
        "Surgery",
        "Unreal Editor",
        "Merchandising",
        "Grocery",
        "IES VE",
        "Certified DDI Facilitator",
        "Immunohistochemistry",
        "Glassfish",
        "Ion Exchange",
        "Jet Ski",
        "Web Analytics",
        "FDMA",
        "Baan ERP",
        "Copy Typing",
        "Xbox One",
        "Lubrication",
        "Intercollegiate Athletics",
        "JIRA",
        "High Availability",
        "AES",
        "TS",
        "IO",
        "Switches",
        "MMORPG",
        "LDOM",
        "PIM-DM",
        "CMake",
        "DVB-RCS",
        "Volunteer Recruiting",
        "Omegamon",
        "Payments",
        "Owners Representative",
        "Health Education",
        "SDH",
        "MVNO",
        "Glaucoma",
        "Yard Signs",
        "XACT",
        "Two-factor Authentication",
        "Digital Journalism",
        "Internal Audit",
        "Economics",
        "Target Identification",
        "Buyer Representation",
        "Mystery Shopping",
        "Ambulatory",
        "Xactly",
        "Affiliate Networks",
        "UTRAN",
        "CWS",
        "SDTM",
        "Credit",
        "CDL Class B",
        "UltraTax CS",
        "Youth Development",
        "Cd",
        "MySQLi",
        "Tgrid",
        "Golf",
        "QuarkXPress",
        "Budgeting",
        "Zenoss",
        "Core Java",
        "YAML",
        "OMT",
        "OH&amp;S",
        "Email Marketing",
        "VLSI",
        "Wellbeing",
        "General Aviation",
        "Customer Relations",
        "Yachting",
        "Rotating Equipment",
        "Store Management",
        "Snoring",
        "TPT",
        "Underwriting",
        "NCover",
        "Wedding DJ",
        "Airline Ticketing",
        "Dyeing",
        "ISO 14001",
        "Fashion Photography",
        "Amazon EBS",
        "SketchUp",
        "Women Owned Business",
        "Amazon Kindle",
        "WordPress",
        "OS X",
        "Iron Ore",
        "Brocade Fibre Switches",
        "Purchase Management",
        "Aquatic Therapy",
        "XAUI",
        "KYC",
        "Youth Ministry",
        "SV",
        "Group Work",
        "IT Management",
        "JavaBeans",
        "FDQM",
        "Nagios",
        "Museum Collections",
        "Job Scheduling",
        "Financial Planning",
        "Transitional Justice",
        "Psychology",
        "RDI",
        "Team Building",
        "VNC",
        "RTL Coding",
        "Bash",
        "Coastal Zone Management",
        "Corporate Tax",
        "GMDSS",
        "PDMS",
        "Capital Equipment Sales",
        "PMO Services",
        "GDI",
        "Qt Creator",
        "Windows 7",
        "NLB",
        "ICT Governance",
        "Yii",
        "Earthworks",
        "Hypnosis",
        "Fine Art",
        "Mac OS",
        "JCE",
        "Japanese",
        "SNF",
        "cXML",
        "Axioma",
        "NDS",
        "Software Testing Life Cycle",
        "XFP",
        "Equity Capital Markets",
        "Abstract Paintings",
        "Clarity FSR",
        "VSEO",
        "Eastern Europe",
        "Land Use Planning",
        "PTCRB",
        "Group Policy",
        "RTM",
        "Security Audits",
        "NSE",
        "FCC",
        "Integration",
        "Affiliate Management",
        "Photo Shoots",
        "Foreign Affairs",
        "SAP BI",
        "FTTP",
        "Juvenile Law",
        "RFI",
        "Air Freight",
        "At-risk",
        "Omnibus",
        "Control Systems Design",
        "HSI",
        "CMMS",
        "MPLS",
        "Olive Oil",
        "NCPDP",
        "MPLS Networking",
        "Telecom BSS",
        "Workforce Planning",
        "OGC Gateway Reviews",
        "BtB",
        "Knee Pain",
        "MQL",
        "Sanction II",
        "SVT",
        "Executive Search",
        "FSI",
        "IBM XIV",
        "WWAN",
        "PyGTK",
        "Organizational Development",
        "BMI",
        "LPAR",
        "Mobile Applications",
        "NWDS",
        "JDO",
        "Occupational Health",
        "HMRC enquiries",
        "Youth Development",
        "Cisco Technologies",
        "OEM contracts",
        "mLearning",
        "Carriage of Goods by Sea",
        "Welding",
        "SS7",
        "Fund Administration",
        "Capital IQ",
        "NIST",
        "Gastroenterology",
        "EMR",
        "Recombinant DNA",
        "NMLS Licensed",
        "Sports Nutrition",
        "Equities",
        "Job Evaluation",
        "New Product Ideas",
        "Rent to Own",
        "Ghostwriting",
        "Analytical Ultracentrifugation",
        "Long-term Care",
        "Ultimate Frisbee",
        "JavaSE",
        "Nanoparticles",
        "BDCs",
        "Drug Development",
        "CD covers",
        "Broadcast Television",
        "ISTQB",
        "TTCN-3",
        "RTO",
        "IVIG",
        "Cross-functional Coordination",
        "JVM",
        "HCS",
        "VTC",
        "NCP",
        "NMT",
        "MDS",
        "Commercial Kitchen Design",
        "CDM",
        "VAS",
        "MBCS",
        "Financial Mgmt",
        "Copywriting",
        "American Welding Society (AWS)",
        "Digital Illustration",
        "iOS Development",
        "Oracle HR",
        "Siding",
        "Eye Exams",
        "EWP",
        "Agency MBS",
        "Github",
        "RSA SecurID",
        "IQ Navigator",
        "Global Marketing",
        "WLAN",
        "OOH",
        "AAP",
        "Start-up Environment",
        "Literature",
        "Performance Tuning",
        "Hydraulic Systems",
        "Air Conditioning",
        "Dynamics",
        "Biodiversity",
        "Identity Management",
        "SQLite",
        "Furniture",
        "GMLAN",
        "Twist",
        "Protein Expression",
        "Yin Yoga",
        "Zoology",
        "CCDA",
        "MFS",
        "GC-FID",
        "Jib",
        "NPI Management",
        "DBUnit",
        "Prenuptial Agreements",
        "Electrical Controls",
        "FMA",
        "Leases",
        "Post Production",
        "CISSP",
        "Fashion Blogging",
        "Robotics",
        "iOS",
        "Multi-color Flow Cytometry",
        "Ownership",
        "VB5",
        "WTX",
        "GPS Applications",
        "eHRPD",
        "OID",
        "Lucene",
        "Project Engineering",
        "IMS DB/DC",
        "NHS Commissioning",
        "EBR",
        "Data Entry",
        "Spring MVC",
        "SFX Editing",
        "xCP",
        "Land Use Planning",
        "Elementary Education",
        "Eye Surgery",
        "Change Orders",
        "GL",
        "Xbox 360",
        "Slip &amp; Fall",
        "Xing",
        "Hand-drawn Typography",
        "HDV",
        "Book Reviews",
        "Automotive Aftermarket",
        "Internet Banking",
        "Customer Engagement",
        "GXT",
        "NCSS",
        "Chi Kung",
        "Credit Risk",
        "AOD",
        "GPGPU",
        "TDMA",
        "Node.js",
        "Key Account Development",
        "NFPA 101",
        "Performance Appraisal",
        "Audio Editing",
        "CQ5",
        "3D Visualization",
        "Functional Verification",
        "Employee Relations",
        "Aviation Security",
        "DMP",
        "Layout",
        "Program Evaluation",
        "Nslookup",
        "Accounting",
        "International Economics",
        "CNC Operation",
        "UCP 600",
        "Acute Care",
        "OTN",
        "PDMS Design",
        "Year End Accounts",
        "Pumps",
        "IT Outsourcing",
        "Special Effects Makeup",
        "People Management",
        "Overseeing Projects",
        "IT Risk Management",
        "DVD Architect",
        "HNI",
        "CWA",
        "Lyricist",
        "CVD",
        "eHealth",
        "VMware VTSP",
        "ICD-9-CM",
        "Pneumatics",
        "RSoft",
        "MSDS",
        "Lymphatic Drainage",
        "Non-profit Leadership",
        "SSL Duality",
        "Green Belt",
        "Sales Presentations",
        "Ocean Transportation",
        "FTP",
        "LAN Switching",
        "HTK",
        "Mortgage Underwriting",
        "Pyxis",
        "CPP",
        "IRB",
        "Focus Groups",
        "RNP",
        "MCEV",
        "Osteoporosis",
        "HCFA",
        "DSLR",
        "Google Earth",
        "GVP",
        "Substance Abuse Prevention",
        "Oil &amp; Gas Law",
        "Experion PKS",
        "XUL",
        "McData",
        "Slope Stability",
        "Power Systems",
        "JCA",
        "Pneumatic Conveying",
        "VO",
        "NCBI",
        "MyChart",
        "Book Design",
        "Grief Counseling",
        "Threat &amp; Vulnerability Management",
        "BMC Remedy Ticketing System",
        "Sustainable Development",
        "TJC",
        "JDK",
        "Finite Element Analysis",
        "PFTrack",
        "Wholesale Operations",
        "RMF",
        "Psychometrics",
        "Government Procurement",
        "Emergency Services",
        "CWSP",
        "Otology",
        "Facilitation",
        "UCITS",
        "Patient Education",
        "Ductwork",
        "NCS",
        "Short Films",
        "Rugby Union",
        "Culture Change",
        "Union",
        "RTB",
        "CTQ",
        "GNU",
        "MTBF",
        "zSeries",
        "Order Picking",
        "TCPA",
        "System Administration",
        "CBM",
        "CEO/CFO Certification",
        "Avid DS Nitris",
        "Yardi Voyager",
        "Irrigation Management",
        "Ozone",
        "DNP3",
        "NPV",
        "Hatha Yoga",
        "Higher Education Administration",
        "Virtual PC",
        "Bloomberg Terminal",
        "OE",
        "Cyber Defense",
        "Eclipse RCP",
        "Microsoft Dynamics SL",
        "PTW",
        "UART",
        "ICT Governance",
        "TSCM",
        "LDO",
        "NGL",
        "PyMEL",
        "Cloud Computing IaaS",
        "DH+",
        "RDz",
        "MCDBA",
        "RS485",
        "DDM",
        "Kernel",
        "Egyptology",
        "MLD",
        "VMware Server",
        "GDP",
        "JMP",
        "KnockoutJS",
        "Silverlight",
        "WinForms",
        "Korean",
        "Fertility",
        "TMAP",
        "Type Design",
        "Graduate Recruitment",
        "EP",
        "Revenue Cycle Management",
        "HRIS",
        "Loss Prevention",
        "Mobile Games",
        "RFC",
        "RTLS",
        "Swaps",
        "QR",
        "Kinematics",
        "Humanitarian",
        "CFDs",
        "Yahoo Search",
        "IDX",
        "HP Blade",
        "Web Design",
        "PXRD",
        "SSI",
        "Language Teaching",
        "AHA",
        "KXEN",
        "RF Circuits",
        "Procurement",
        "NBFC",
        "Participant Observation",
        "PMD",
        "Hazard Identification",
        "Kaspersky",
        "Organization Skills",
        "Vehicle Dynamics",
        "QlikView Development",
        "Creative Non-fiction",
        "Hyperion",
        "Recruiting",
        "QA Automation",
        "Irrigation",
        "RWA",
    ];
}
