<?php

use App\Tag;
use Illuminate\Database\Seeder;

class TagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->tags as $tag) {
            Tag::create(['tag' => $tag]);
        }
    }

    private $tags = [
        "FPGA",
        "Group Therapy",
        "Police",
        "NCS",
        "ISO 22000",
        "Investment Properties",
        "Navigation",
        "Media Planning",
        "Statistics",
        "XML Spy",
        "Retirement Planning",
        "Real Estate Transactions",
        "Abaqus",
        "Jimmy Jib",
        "OEIC",
        "PXE",
        "Music Education",
        "Online Help",
        "Publicity",
        "Vocational Rehabilitation",
        "Rail",
        "Capital Equipment",
        "PTS",
        "CVIS",
        "CBM",
        "Medical Billing",
        "Vocal Coaching",
        "Mechanical Engineering",
        "RCS",
        "IBM BPM",
        "Medical-Surgical",
        "Inspection",
        "Operational Planning",
        "Clinical Psychology",
        "WCDMA",
        "RTK",
        "Pre-sales",
        "Title Insurance",
        "HTRF",
        "ATP",
        "PXRD",
        "GMAT",
        "Adobe Creative Suite",
        "Data Migration",
        "EPM",
        "Olefins",
        "Global Operations",
        "Outside Sales",
        "Ghost Imaging",
        "PPAP",
        "KVM",
        "FMCG",
        "OECD",
        "QlikView Development",
        "TS",
        "IDX",
        "JDE CNC",
        "FDICIA",
        "Orthopedics",
        "Apache",
        "Direct Mail",
        "jQuery",
        "Oil Painting",
        "21 CFR",
        "Mycobacteriology",
        "Utilization Management",
        "BPML",
        "Air Conditioning",
        "OTN",
        "CVIS",
        "Quantitative Analytics",
        "IRAs",
        "Ubercart",
        "CMC",
        "Kaizen Blitz",
        "eGain",
        "InfoComm CTS",
        "Xplan",
        "Hydropower",
        "Database Marketing",
        "CCSP",
        "JSR 168",
        "Americans with Disabilities Act",
        "NX-OS",
        "Ableton Live",
        "Cisco IOS",
        "DVB-S",
        "Xen",
        "Two-way Radio",
        "MRP",
        "In-situ Chemical Oxidation",
        "ICEM CFD",
        "Ulead VideoStudio",
        "Westlaw",
        "Reactive Ion Etching",
        "Union Avoidance",
        "NVU",
        "Accounting",
        "JAX-RPC",
        "Windows 7",
        "Ehcache",
        "Twitter Marketing",
        "PDMLink",
        "Financial Services",
        "UV disinfection",
        "PSpice",
        "Bylaws",
        "Aerospace Engineering",
        "Life Sciences",
        "Overcoming Challenges",
        "VxFS",
        "IGCC",
        "BDC programming",
        "UV/Vis",
        "Kodak",
        "Lubricants",
        "EH&amp;S Compliance",
        "Toad",
        "RBAC",
        "TBS",
        "Railway",
        "SAP MM",
        "FCNSA",
        "NFS",
        "Behavioral Health",
        "Animal Nutrition",
        "3Com NBX",
        "Biopharmaceuticals",
        "OnQ",
        "QSIG",
        "Ionic Liquids",
        "Winning Others Over",
        "Events Organisation",
        "Underwriting",
        "CMS-1500",
        "GWAPT",
        "Medical Ultrasound",
        "CMiC",
        "UHV",
        "Cluster",
        "Food Processing",
        "MPEG",
        "DDR3",
        "TV series",
        "Olefins",
        "Workforce Development",
        "FS-CD",
        "KDevelop",
        "MLRO",
        "GAAP",
        "Simple IRA",
        "Cash Flow Forecasting",
        "XUL",
        "Threat &amp; Vulnerability Management",
        "AJAX",
        "Yellow Belt",
        "Credit Analysis",
        "SEM",
        "Yield Management",
        "Keynote",
        "Optical Tweezers",
        "HtmlUnit",
        "Immigration Law",
        "RDBMS",
        "Hodes IQ",
        "Wind",
        "TMAP",
        "SMO",
        "Jigs",
        "TUPE",
        "Leadership Development",
        "QROPS",
        "MyEclipse",
        "IRS Enrolled Agent",
        "Client Aquisition",
        "MCSD",
        "Architecture",
        "National Association of Realtors",
        "SMT",
        "Graphic Design",
        "Scanning Electron Microscopy",
        "Multi-channel Marketing",
        "Window Displays",
        "TMF",
        "Slideshare",
        "Cross-functional Coordination",
        "Holistic Health",
        "RCSA",
        "FTPS",
        "User Experience",
        "Drug Development",
        "Commercial Litigation",
        "Corporate FP&amp;A",
        "MySQL Cluster",
        "Cisco Technologies",
        "Plant Identification",
        "Dysarthria",
        "Radiology",
        "VHDL-AMS",
        "Krav Maga",
        "Hydraulics",
        "TWiki",
        "Emerging Markets",
        "Turbo Pascal",
        "TJC",
        "Agarose Gel Electrophoresis",
        "Area Rugs",
        "FQHC",
        "VM",
        "Operational Due Diligence",
        "Volunteer Management",
        "Mental Health Counseling",
        "EP",
        "Global Mobility",
        "Global Custody",
        "Drupal",
        "Sound",
        "SNAP",
        "Adolescents",
        "Technical Writing",
        "UDS",
        "Physical Security",
        "Avid Newscutter",
        "Community Outreach",
        "Online Publishing",
        "Information Assurance",
        "BGAN",
        "Appeals",
        "MX960",
        "iWork",
        "IRS",
        "Athlete Development",
        "Construction Drawings",
        "JSA",
        "JBPM",
        "Amadeus GDS",
        "US Tax",
        "Hypnosis",
        "VLDB",
        "RTOS",
        "Volunteering",
        "Sh",
        "Waste",
        "CD packaging",
        "Military Operations",
        "nMarket",
        "MCAD",
        "XML Gateway",
        "Personnel Management",
        "Whisky",
        "SaaS",
        "International Sales",
        "Media Relations",
        "Cerner CCL",
        "CentOS",
        "OAT",
        "GNU Debugger",
        "Quality Auditing",
        "Electrical Troubleshooting",
        "Utility Systems",
        "International Shipping",
        "ISO",
        "MySQL Cluster",
        "SharePoint Designer",
        "CDMA",
        "Equities",
        "Process Improvement",
        "Cisco Nexus",
        "CCIE",
        "Spreadsheets",
        "PTCRB",
        "Embedded Software",
        "Amazon Kindle",
        "Vectorworks",
        "P&amp;ID",
        "RMS",
        "Snoring",
        "Two-photon Microscopy",
        "Nanofabrication",
        "NSS",
        "HMS",
        "Automobile",
        "Usability Testing",
        "NDT",
        "Frozen Food",
        "Cycle Counting",
        "Offshore Outsourcing",
        "Gypsum",
        "Equity Research",
        "JUNOS",
        "Accounting",
        "XBRL",
        "MDA",
        "Sun One LDAP",
        "FCC License",
        "Wellbeing",
        "XFOIL",
        "Long Distance Running",
        "Three.js",
        "Economic Policy",
        "Nuke",
        "IEF",
        "US GAAP",
        "PML",
        "Customer Support",
        "AFM",
        "Juniper Switches",
        "Wellness",
        "Ocean",
        "Kurzweil",
        "Business Process",
        "HP Procurve Networking",
        "Oracle RAC",
        "Xytech",
        "Variance Analysis",
        "Orchestral Music",
        "LCD TV",
        "Zuora",
        "VTL",
        "MQC",
        "Fashion Illustration",
        "Workforce Development",
        "User Experience",
        "TDMA",
        "Software Engineering",
        "CVIS",
        "Corporate Identity",
        "Nintex",
        "Software Testing Life Cycle",
        "CMOS",
        "1H NMR",
        "Global Human Resources Management",
        "SMT Kingdom",
        "MTBF",
        "Cost Benefit",
        "RSView",
        "Oxides",
        "RCFA",
        "Zumba Instruction",
        "Higher Education",
        "IEC",
        "Acute Care",
        "Getting to Yes",
        "Tires",
        "OSHA 30-Hour",
        "Current Affairs",
        "Land Development",
        "Quantitative Research",
        "SQLite",
        "Woodworking",
        "Xoops",
        "Technical Recruiting",
        "LCD Projectors",
        "CRM",
        "AFM",
        "Multiplex PCR",
        "Customer Relations",
        "Athletic Performance",
        "Rent to Own",
        "Omnis",
        "FDICIA",
        "WebLogic",
        "CWSP",
        "CMMS",
        "Clinical Research",
        "Smart Grid",
        "Pylons",
        "Reaction Kinetics",
        "DSLR",
        "FFT",
        "Slate",
        "CDO",
        "WordPress",
        "Variable Frequency Drives",
        "IABP",
        "LLDPE",
        "Ion",
        "GPP",
        "PCB Design",
        "GMF",
        "RBD",
        "Waste",
        "IACUC",
        "LDI",
        "Dublin Core",
        "Coaching",
        "Downstream Oil &amp; Gas",
        "Twitter",
        "JCA",
        "Airline Management",
        "WTT",
        "DCN",
        "JBoss ESB",
        "jBase",
        "Chronic Illness",
        "Big 4",
        "Kenan FX",
        "Classroom Management",
        "Lymphoma",
        "Solvency II",
        "Qualitative Research",
        "CP",
        "FpML",
        "Requirements Analysis",
        "FMVSS",
        "PDF Creator",
        "Data Quality",
        "Criminal Law",
        "Hospitality",
        "Workforce Management",
        "Oracle HR",
        "Iyengar Yoga",
        "SDL Tridion",
        "DCF Valuation",
        "Land Development",
        "DFT Compiler",
        "Ozone Therapy",
        "MMI",
        "Telecom BSS",
        "Residential Mortgages",
        "Awk",
        "Hospitality",
        "EP",
        "Capacity Building",
        "LTSP",
        "CME",
        "FS-CD",
        "International Law",
        "IT Outsourcing",
        "Curriculum Development",
        "Customs Regulations",
        "RDBMS",
        "Kundalini Yoga",
        "Labor Relations",
        "DDA",
        "FMA",
        "Jive SBS",
        "RFC",
        "GNMA",
        "Corporate FP&amp;A",
        "FrameMaker",
        "IBC",
        "LDI",
        "Amazon VPC",
        "vShield",
        "Medical Writing",
        "GSP",
        "Custom Furniture",
        "Design Patterns",
        "PGP",
        "LSS",
        "Screenwriting",
        "Github",
        "OSHA Instruction",
        "Kaizen",
        "NDK",
        "VSAT",
        "Custom Furniture",
        "Play-by-play",
        "Mac OS X Server",
        "Internet Banking",
        "Fluorescence Microscopy",
        "Ghost Imaging",
        "Microsoft Office",
        "Technical Support",
        "TV Distribution",
        "WSGI",
        "SEO",
        "HTML Help Workshop",
        "Life Sciences",
        "PDS Frameworks",
        "Pastoral Care",
        "Snorkeling",
        "AWS CWI",
        "Euthanasia",
        "Flame AA",
        "Nuclear",
        "SAP SD Module",
        "Easytrieve",
        "CFK",
        "Customs Regulations",
        "LDO",
        "cGLP",
        "Power Generation",
        "Visio",
        "PMI",
        "MCSA + Messaging",
        "LCSH",
        "RMA",
        "Radio Broadcasting",
        "RPG III",
        "DNS",
        "GMI",
        "Client Relations",
        "Airline Ticketing",
        "Ocular Disease",
        "SFI",
        "DTH",
        "Real Estate Transactions",
        "DP",
        "VTR",
        "OJEU",
        "Bylaws",
        "nCloth",
        "Land Development",
        "MD5",
        "JTA",
        "ETAP",
        "Ufile",
        "Nitric Oxide",
        "GTS",
        "FSI",
        "International Shipping",
        "PDA",
        "FMVSS",
        "Autism Spectrum Disorders",
        "Human Rights",
        "Trading Systems",
        "Zephyr",
        "Jeet Kune Do",
        "Home Care",
        "Yard Management",
        "Rhapsody",
        "QKA",
        "HTML",
        "Corporate Identity",
        "Online Lead Generation",
        "FX Operations",
        "TV News Production",
        "UCP",
        "Brain Gym",
        "General Aviation",
        "HMDA",
        "HP Service Manager",
        "Special Events",
        "Global Custody",
    ];
}
